"""Build the single-file, offline browser edition from the reviewed web sources.

The generated HTML deliberately has no network dependency.  It is useful on a
locked-down PC when GitHub Pages has not been enabled yet: download the file,
open it in a browser, paste text, and work locally.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re


PROJECT_ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = PROJECT_ROOT / "web"
OUTPUT_PATH = WEB_ROOT / "TextVerbessern-Browser.html"
STYLESHEET_TAG = '<link rel="stylesheet" href="./styles.css">'
MODULE_TAG = '<script type="module" src="./app.js"></script>'
EDITOR_IMPORT = re.compile(
    r'^import \{.*?^\} from "\./editor\.js";\s*',
    flags=re.DOTALL | re.MULTILINE,
)


def _read(name: str) -> str:
    return (WEB_ROOT / name).read_text(encoding="utf-8")


def _inline_editor_source(source: str) -> str:
    """Turn the small ESM editor module into code for one ordinary script tag."""
    converted = re.sub(r"^export ", "", source, flags=re.MULTILINE)
    if "export " in converted:
        raise ValueError("Unsupported export in web/editor.js")
    return converted


def _inline_app_source(source: str) -> str:
    """Remove the sole ESM import; editor symbols share the same script scope."""
    converted, replacements = EDITOR_IMPORT.subn("", source, count=1)
    if replacements != 1:
        raise ValueError("Could not locate the web/editor.js import in web/app.js")
    if "import " in converted:
        raise ValueError("Unsupported import in web/app.js")
    return converted


def render() -> str:
    """Return the deterministic offline HTML document."""
    page = _read("index.html")
    stylesheet = _read("styles.css")
    editor = _inline_editor_source(_read("editor.js"))
    application = _inline_app_source(_read("app.js"))

    if STYLESHEET_TAG not in page or MODULE_TAG not in page or "</body>" not in page:
        raise ValueError("Expected browser assets are missing from web/index.html")
    if "</style" in stylesheet.lower() or "</script" in editor.lower() or "</script" in application.lower():
        raise ValueError("A source asset cannot safely be embedded in the standalone HTML")

    page = page.replace(
        "script-src 'self'; style-src 'self';",
        "script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';",
        1,
    )
    if "connect-src 'none'" not in page:
        raise ValueError("Standalone edition must forbid network connections")
    # Replace complete indented asset lines. Replacing only the tag leaves the
    # indentation of the removed module tag behind as a whitespace-only line
    # in the generated document.
    stylesheet_line = f"    {STYLESHEET_TAG}"
    module_line = f"    {MODULE_TAG}\n"
    if stylesheet_line not in page or module_line not in page:
        raise ValueError("Expected indented browser asset lines are missing from web/index.html")
    page = page.replace(
        stylesheet_line,
        f"    <style>\n{stylesheet.rstrip()}\n    </style>",
        1,
    )
    page = page.replace("Text verbessern – Browser-Ausgabe", "Text verbessern – Offline-Ausgabe", 1)
    page = page.replace("TEXT VERBESSERN · BROWSER-AUSGABE", "TEXT VERBESSERN · OFFLINE-AUSGABE", 1)
    page = page.replace(
        "GitHub Pages liefert nur die Programmdateien aus.",
        "Diese lokale Datei verbindet sich nicht mit GitHub oder anderen Diensten.",
        1,
    )
    inline_script = "\n".join(
        (
            "<script>",
            "// Generated by scripts/build_browser_standalone.py; do not edit by hand.",
            editor,
            application,
            "</script>",
        )
    )
    page = page.replace(module_line, "", 1)
    return page.replace("</body>", f"{inline_script}\n  </body>", 1)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the standalone browser edition.")
    parser.add_argument("--check", action="store_true", help="fail when the generated file is outdated")
    arguments = parser.parse_args()
    generated = render()

    if arguments.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != generated:
            print(f"{OUTPUT_PATH.relative_to(PROJECT_ROOT)} is outdated; run this script to regenerate it.")
            return 1
        print(f"{OUTPUT_PATH.relative_to(PROJECT_ROOT)} is up to date.")
        return 0

    OUTPUT_PATH.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
